# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(402, 383))
        MainWindow.setMaximumSize(QtCore.QSize(402, 383))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/clamguard/images/Gerald-G-Clam-Security-Guard-ico32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trvSystem = QtWidgets.QTreeView(self.centralwidget)
        self.trvSystem.setGeometry(QtCore.QRect(10, 10, 381, 321))
        self.trvSystem.setObjectName("trvSystem")
        self.btnScan = QtWidgets.QPushButton(self.centralwidget)
        self.btnScan.setGeometry(QtCore.QRect(10, 340, 87, 29))
        self.btnScan.setObjectName("btnScan")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(100, 340, 87, 29))
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnViewLogs = QtWidgets.QPushButton(self.centralwidget)
        self.btnViewLogs.setGeometry(QtCore.QRect(190, 340, 87, 29))
        self.btnViewLogs.setObjectName("btnViewLogs")
        self.btnViewQuarantine = QtWidgets.QPushButton(self.centralwidget)
        self.btnViewQuarantine.setGeometry(QtCore.QRect(280, 340, 111, 29))
        self.btnViewQuarantine.setObjectName("btnViewQuarantine")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ClamGuard"))
        self.btnScan.setText(_translate("MainWindow", "Scan"))
        self.btnUpdate.setText(_translate("MainWindow", "Update"))
        self.btnViewLogs.setText(_translate("MainWindow", "View Logs"))
        self.btnViewQuarantine.setText(_translate("MainWindow", "View Qurantine"))


import resourses_rc
