# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Quarantine.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuarantineWindow(object):
    def setupUi(self, QuarantineWindow):
        QuarantineWindow.setObjectName("QuarantineWindow")
        QuarantineWindow.resize(758, 423)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuarantineWindow.sizePolicy().hasHeightForWidth())
        QuarantineWindow.setSizePolicy(sizePolicy)
        QuarantineWindow.setMinimumSize(QtCore.QSize(758, 423))
        QuarantineWindow.setMaximumSize(QtCore.QSize(758, 423))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/clamguard/Gerald-G-Clam-Security-Guard-ico32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuarantineWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(QuarantineWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(340, 380, 87, 29))
        self.btnClose.setObjectName("btnClose")
        self.trvQuarantine = QtWidgets.QTreeView(self.centralwidget)
        self.trvQuarantine.setGeometry(QtCore.QRect(10, 30, 741, 341))
        self.trvQuarantine.setObjectName("trvQuarantine")
        self.lblItems = QtWidgets.QLabel(self.centralwidget)
        self.lblItems.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.lblItems.setObjectName("lblItems")
#        QuarantineWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(QuarantineWindow)
        self.btnClose.clicked.connect(QuarantineWindow.close)
        QtCore.QMetaObject.connectSlotsByName(QuarantineWindow)

    def retranslateUi(self, QuarantineWindow):
        _translate = QtCore.QCoreApplication.translate
        QuarantineWindow.setWindowTitle(_translate("QuarantineWindow", "View Quarantine"))
        self.btnClose.setText(_translate("QuarantineWindow", "Close"))
        self.lblItems.setText(_translate("QuarantineWindow", "Items in quarantine:"))
import resourses_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuarantineWindow = QtWidgets.QMainWindow()
    ui = Ui_QuarantineWindow()
    ui.setupUi(QuarantineWindow)
    QuarantineWindow.show()
    sys.exit(app.exec_())
