# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateWindow(object):
    def setupUi(self, UpdateWindow):
        UpdateWindow.setObjectName("UpdateWindow")
        UpdateWindow.resize(758, 423)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UpdateWindow.sizePolicy().hasHeightForWidth())
        UpdateWindow.setSizePolicy(sizePolicy)
        UpdateWindow.setMinimumSize(QtCore.QSize(758, 423))
        UpdateWindow.setMaximumSize(QtCore.QSize(758, 423))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/clamguard/Gerald-G-Clam-Security-Guard-ico32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UpdateWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(UpdateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUpdate = QtWidgets.QLabel(self.centralwidget)
        self.lblUpdate.setGeometry(QtCore.QRect(10, 10, 141, 17))
        self.lblUpdate.setObjectName("lblUpdate")
        self.txtUpdate = QtWidgets.QTextEdit(self.centralwidget)
        self.txtUpdate.setGeometry(QtCore.QRect(10, 30, 731, 341))
        self.txtUpdate.setObjectName("txtUpdate")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(320, 380, 87, 29))
        self.btnClose.setObjectName("btnClose")
        # UpdateWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpdateWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateWindow)

    def retranslateUi(self, UpdateWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateWindow.setWindowTitle(_translate("UpdateWindow", "Update Virus Signatures"))
        self.lblUpdate.setText(_translate("UpdateWindow", "Update Virus Signatures"))
        self.btnClose.setText(_translate("UpdateWindow", "Close"))
import resourses_rc
