# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewLogs.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogsWindow(object):
    def setupUi(self, LogsWindow):
        LogsWindow.setObjectName("LogsWindow")
        LogsWindow.resize(758, 423)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LogsWindow.sizePolicy().hasHeightForWidth())
        LogsWindow.setSizePolicy(sizePolicy)
        LogsWindow.setMinimumSize(QtCore.QSize(758, 423))
        LogsWindow.setMaximumSize(QtCore.QSize(758, 423))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/clamguard/Gerald-G-Clam-Security-Guard-ico32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogsWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LogsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(320, 380, 87, 29))
        self.btnClose.setObjectName("btnClose")
        self.cmbLogs = QtWidgets.QComboBox(self.centralwidget)
        self.cmbLogs.setGeometry(QtCore.QRect(10, 20, 641, 25))
        self.cmbLogs.setObjectName("cmbLogs")
        self.btnDeleteLog = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteLog.setGeometry(QtCore.QRect(660, 20, 87, 29))
        self.btnDeleteLog.setObjectName("btnDeleteLog")
        self.trvLogDetails = QtWidgets.QTreeView(self.centralwidget)
        self.trvLogDetails.setGeometry(QtCore.QRect(10, 50, 741, 321))
        self.trvLogDetails.setObjectName("trvLogDetails")
        # LogsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogsWindow)
        self.btnClose.clicked.connect(LogsWindow.close)
        QtCore.QMetaObject.connectSlotsByName(LogsWindow)

    def retranslateUi(self, LogsWindow):
        _translate = QtCore.QCoreApplication.translate
        LogsWindow.setWindowTitle(_translate("LogsWindow", "Logs"))
        self.btnClose.setText(_translate("LogsWindow", "Close"))
        self.btnDeleteLog.setText(_translate("LogsWindow", "Delete Log"))
import resourses_rc
